### ISSUE TITLE
Won't work with node.js

### ISSUE THREAD

**Issue by pgn-vole** [paldepind/snabbdom#84]
The `style` module seems to crash when using within Node.js.
Without requiring it everything seems to work fine.

```javascript
 C:\UBS\Dev\components\nav\node_modules\snabbdom\modules\style.js:1
 (function (exports, require, module, __filename, __dirname) { var raf = (window && window.requestAnimationFrame) || setTimeout;

ReferenceError: window is not defined
```

I cannot see mention of Node.js within the README. Is it not officially supported ?

**Comment by chrisdotcode** [comment]
I don't think snabbdom does or doesn't work explicitly with or without Node - snabbdom is intended for browser-like environments, and Node is not one by default. It's missing stuff like `window` and `document`.

**Comment by leeoniya** [comment]
domvm is also browser-first, but isomorphism/SSR works fine in Node to generate a vtree and spit out attachable html. If you restrict the problem space to this, then snabbdom could be made to work i think. if you're looking for the full test suite to pass, you're probably SOL without huge dom-polyfilling dependencies.

**Comment by TylorS** [comment]
You should try using [snabbdom-to-html](http://github.com/acstll/snabbdom-to-html) if you need to render HTML on node

**Comment by leeoniya** [comment]
@TylorS

can you "liven' the tree after the server returns the html or is it necessary to fully re-render the ui on the client?

**Comment by TylorS** [comment]
Well if you want things like event listeners to attach you'll have to do some re-rendering on the client

**Comment by paldepind** [comment]
I've just published a bugfix release to npm with the patch by @staltz in #85. Unless I'm mistaken it should resolve the issue here.

**Comment by pgn-vole** [comment]
thanks @paldepind !

**Comment by masaeedu** [comment]
@paldepind Still seeing this issue. I have a simple library for which I want to run the tests on node by diffing two vnodes without any concrete DOM involved. I can't see a way to do this with snabbdom.

If I do:

```js
patch(h("div"), h("div", [h("div")]));
```

**Comment by caridy** [comment]
I don't think you will be able to run snabbdom on the server if you don't have [jsdom](https://www.npmjs.com/package/jsdom), or use a test runner that provides jsdom out of the box (e.g.: jest from facebook). The patch from @staltz in #85 is useful because jsdom does not ship with `requestAnimationFrame`, in which case it must be polyfilled, which is what the patch does anyways.
